language: node_js
node_js:
  - 14
deploy: 
  provider: npm
  email: $EMAIL_ADDRESS
  skip_cleanup: true
  api_key: $AUTH_TOKEN
  on: 
    tags: true
    branch: main
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'